# roles/bind/tasks/main.yml
---

- name: Check whether `bind_zone_master_server_ip` was set
  assert:
    that: bind_zone_master_server_ip is defined

- name: Install BIND
  yum:
    pkg: "{{ item }}"
    state: installed
  with_items: bind_packages_centos
  tags: bind

- name: Install DNSSec extras
  yum:
    pkg: "{{ item }}"
    state: installed
  with_items: 
    - haveged
  when: bind_enable_dnssec == true
  tags: bind

- name: Start Haveged
  service:
    name: haveged
    state: started
    enabled: yes
  when: bind_enable_dnssec == true
  tags: bind

- name: Install BIND Chroot Packages
  yum:
    pkg: "{{ item }}"
    state: installed
  with_items: 
    - bind-chroot
  when: bind_chroot == true
  tags: bind

- name: Create serial
  command: date +%y%m%d%H
  register: timestamp
  tags: bind

- include: master.yml
  when: ansible_all_ipv4_addresses|last == bind_zone_master_server_ip

- include: slave.yml
  when: not ansible_all_ipv4_addresses|last == bind_zone_master_server_ip

- name: Start BIND service
  service:
    name: named
    state: started
    enabled: yes
  tags: bind

