# roles/bind/tasks/master.yml
# Set up a BIND master server
---

- name: Main BIND config file (master)
  template:
    src: master_etc_named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: '0640'
    setype: named_conf_t
#    validate: 'named-checkconf %s'
  notify: restart bind
  tags: bind

- name: Create Zones - DNSSEC
  include: master-generate-dnssec-zones.yml
  when: bind_enable_dnssec == true

- name: Create Zones - Non DNSSEC
  include: master-generate-zones.yml
  when: bind_enable_dnssec == false
