# roles/bind/tasks/master.yml
# Set up a BIND master server
---

- name: Main BIND config file (master)
  template:
    src: master_etc_named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: '0640'
    setype: named_conf_t
#    validate: 'named-checkconf %s'
  notify: restart bind
  tags: bind

######### With Ansible 2.0, we neaten what happend below
#- name: build zone files
#  include: master-zones.yml
#  with_items: bind_master_zones

- name: build latest serial
  shell: DATE=`date "+%H%M"`; INCR=$(($DATE / 24)); echo `date "+%Y%m%d"`$INCR
  register: named_serial
  tags: bind
########### Note: This has the caveat that the serial will only change when calculated once every 14 minutes throughout the day

- debug: var=named_serial
  tags: bind

- name: Create forward lookup zone file
  template:
    src: multi_bind_zone.j2
    dest: "{{ bind_zonefile_location }}/{{ item.zone_name }}"
    owner: root
    group: named
    mode: "0640"
    setype: named_zone_t
#    validate: "named-checkzone {{ item.zone_name }} %s"
  notify: restart bind
  tags: bind
  when: bind_enable_dnssec == true
  with_items: bind_master_zones
  when: bind_master_zones is defined


- name: Create forward lookup zone file
  template:
    src: bind_zone.j2
    dest: "/var/named/{{ bind_zone_name }}"
    owner: root
    group: named
    mode: "0640"
    setype: named_zone_t
    validate: "named-checkzone {{  bind_zone_name }} %s"
  notify: restart bind
  tags: bind
  when: bind_master_zones is not defined

- name: Create reverse lookup zone file
  template:
    src: multi_reverse_zone.j2
    dest: "/var/named/{{ item|reverse_lookup_zone }}"
    owner: root
    group: named
    mode: "0640"
    setype: named_zone_t
#    validate: "named-checkzone {{ item|reverse_lookup_zone }} %s"
  with_items: bind_zone_networks
  notify: restart bind
  tags: bind
  when: bind_master_zones is defined

- name: Create reverse lookup zone file
  template:
    src: reverse_zone.j2
    dest: "/var/named/{{ item|reverse_lookup_zone }}"
    owner: root
    group: named
    mode: "0640"
    setype: named_zone_t
    validate: "named-checkzone {{ item|reverse_lookup_zone }} %s"
  with_items: bind_zone_networks
  notify: restart bind
  tags: bind
  when: bind_master_zones is not defined
